---
apiVersion: v1
kind: Pod
metadata:
  name: openpose
spec:
  volumes:
  - hostPath:
      path: /var/lib/nvidia-docker/volumes/nvidia_driver/375.82
    name: nvidia-driver
  containers:
  - name: openpose
    image: mjsobrep/openpose
    command: ["/bin/bash"]
    args: ["-c", "trap : TERM INT; sleep infinity & wait"]
    resources:
      limits:
        alpha.kubernetes.io/nvidia-gpu: 1
    volumeMounts:
    - mountPath: /usr/local/nvidia
      name: nvidia-driver
